### PR TITLE
fix: cairo-m guest compilation 

### LINKED ISSUE #136: Compile Cairo-M guest only once
As the serialization of Cairo-M guest was fixed in https://github.com/kkrt-labs/cairo-m/issues/348, we can follow the shared state approach from https://github.com/privacy-ethereum/csp-benchmarks/pull/94 to avoid recompiling the guest before each benchmark run.

### PR DESCRIPTION
**Pull request by brech1**
# Description

Separate `cairo-m` program compilation from input preparation.

## Changes

- Pin cairo-m dependencies to rev `79c1b1e`
- Extract `compile_program()` as a separate function
- Update benchmark harness to use separate compile and prepare phases
- Update `sha256_mem.rs` binary to use the new API

## Related Issues

- Resolves #136

### CODE REVIEW

File: cairo-m/benches/sha256_bench.rs [hunk 1]
```diff
@@ -22,14 +22,15 @@ utils::define_benchmark_harness!(
...
+    |input_size, program: &Program| { prepare(input_size, program) },
+    |_, _| 0,
+    |(program, (entrypoint_name, runner_inputs)), _: &&Program| {
         prove(program, (entrypoint_name, runner_inputs))
     },
-    |_, proof| { verify(proof) },
-    |(compiled_program, _)| { compiled_program.len() },
-    |proof| proof.stark_proof.size_estimate(),
+    |_, proof, _| { verify(proof) },
+    |(compiled_program, _), _: &&Program| { compiled_program.len() },
```
Comment (alxkzmn) [inline cairo-m/benches/sha256_bench.rs]: I think it's ok to not specify the type if the variable is not used

Comment (alxkzmn) [inline cairo-m/benches/sha256_bench.rs]:
```suggestion
    |(compiled_program, _), _| { compiled_program.len() },
```

File: cairo-m/benches/sha256_bench.rs [hunk 2]
```diff
@@ -22,14 +22,15 @@ utils::define_benchmark_harness!(
...
+    |proof, _: &&Program| proof.stark_proof.size_estimate(),
```
Comment (alxkzmn) [inline cairo-m/benches/sha256_bench.rs]:
```suggestion
    |proof, _| proof.stark_proof.size_estimate(),
```

File: cairo-m/benches/sha256_bench.rs [hunk 3]
```diff
@@ -22,14 +22,15 @@ utils::define_benchmark_harness!(
         AuditStatus::NotAudited, // https://github.com/kkrt-labs/cairo-m/?tab=readme-ov-file#about
         Some("Cairo ISA"), // https://github.com/kkrt-labs/cairo-m/blob/main/docs/design.md
     ),
-    |input_size| { prepare(input_size) },
-    |_| 0,
-    |(program, (entrypoint_name, runner_inputs))| {
+    { compile_program() },
+    |input_size, program: &Program| { prepare(input_size, program) },
+    |_, _| 0,
+    |(program, (entrypoint_name, runner_inputs)), _: &&Program| {
```
Comment (alxkzmn) [inline cairo-m/benches/sha256_bench.rs]:
```suggestion
    |(program, (entrypoint_name, runner_inputs)), _| {
```

**Review by alxkzmn — APPROVED** [review]
LGTM!
