### PR TITLE
fix: bb preprocessing measurement

### LINKED ISSUE #173: Fix BB preprocessing (CRS) measurement
Barretenberg backend CLI [downloads](https://github.com/AztecProtocol/aztec-packages/blob/next/barretenberg/crs/bootstrap.sh) a CRS file of a size necessary to compile a given circuit. On OSX the download location is `~/.bb-crs`. The size varies with the circuit size (e.g., 4.2 MB for our SHA-256 with 128 B input and 16.8 MB for 2048 B input). Therefore, we need to extend the [preprocessing measurement](https://github.com/privacy-ethereum/csp-benchmarks/blob/CSP-Q3-2025/barretenberg/_measure_common.sh) with the following:
- clear the `~/.bb-crs` folder
- run a single proof for the given size
- measure the contents of the `~/.bb-crs`
- side note: consider moving the measurements before the prover benchmark to avoid including the CRS download time into the first benchmarking run.

### PR DESCRIPTION
**Pull request by brech1**
# Description

Add CRS size measurement to preprocessing and ensure CRS download time is excluded from prover benchmarks.

## Changes

- Implement `bb_clear_crs()` and `bb_measure_crs_size()` helpers
- Include CRS size in `preprocessing_size` calculation
- Move size measurement before prover benchmark to pre-download CRS

## Related Issues

- Closes #173

### CODE REVIEW

**Comment by brech1** [comment]
Preprocessing size now correctly includes CRS:

| Circuit | Input | Before | Now     |
|---------|-------|--------|---------|
| sha256  | 128B  | 98 KB  | 4.1 MB  |
| sha256  | 2KB   | 842 KB | 16.8 MB |
| ecdsa   | 32B   | 2.9 KB | 8.0 MB  |
  
Before: https://github.com/privacy-ethereum/csp-benchmarks/actions/runs/19489495243/artifacts/4609639825
Now: https://github.com/privacy-ethereum/csp-benchmarks/actions/runs/19772585449/artifacts/4709802401

File: barretenberg/_measure_common.sh [hunk 1]
```diff
@@ -30,13 +53,14 @@ bb_write_sizes_and_constraints() {
...
-  preprocessing_size_bytes=$(( circuit_size ))
+  preprocessing_size_bytes=$(( circuit_size + CRS_SIZE_BYTES ))
 
   local json_output
   json_output=$(jq -n \
     --argjson proof_size "$proof_size_bytes" \
     --argjson preprocessing_size "$preprocessing_size_bytes" \
-    '{proof_size: $proof_size, preprocessing_size: $preprocessing_size}')
+    --argjson crs_size "$CRS_SIZE_BYTES" \
+    '{proof_size: $proof_size, preprocessing_size: $preprocessing_size, crs_size: $crs_size}')
```
Comment (alxkzmn) [inline barretenberg/_measure_common.sh]: Here we don't need to write out `crs_size` separately - it won't be read by any code later. `format_hyperfine.rs` only expects `proof_size` and `preprocessing_size` in `..._sizes.json`.

**Review by alxkzmn — CHANGES_REQUESTED** [review]
Let's remove the crs_size from _sizes. json.

**Review by alxkzmn — APPROVED** [review]
LGTM!
